### ISSUE TITLE
Fungible Sauce Checklist

### ISSUE THREAD

**Issue by ptau211** [jwri211/openSauce#6]
- [x] Is the Sauce desirable?
- [x] Can it be sold as NFT?
- [x] So, what's next?

**Comment by ssimons23** [comment]
How are you guys

**Comment by jwri211** [comment]
NFT Sauce is the next big thing!

**Comment by Mikelabu** [comment]
I feel left out. I have Never tasted NFT Sauce before
